language: php

php:
  - 5.5
  - 5.4

before_script:
  - composer self-update
  - composer update

script:
  - php ./vendor/bin/phpunit -c ./tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
